### ISSUE TITLE
MAX_ANIMATORS

### ISSUE THREAD

**Issue by jdkDollaR** [alexchwoj/pawn-easing-functions#12]
The  'MAX ANIMATORS' has a value of '1024', that is, a maximum of '1024' animations can occur on the server or is it '1024' for each player?

**Comment by alexchwoj** [comment]
Hi,

It is the maximum of all animations at the same time.

**Comment by jdkDollaR** [comment]
> Hi,
> 
> It is the maximum of all animations at the same time.

So only '1024' animations that can occur on the entire server? Isn't it just for the player?

**Comment by alexchwoj** [comment]
Exactly, anyway I can't think of any context where you can exceed that limit.

**Comment by jdkDollaR** [comment]
The idea of ​​the include is really very good and very interesting, when I saw this include I was quite excited but when I put it into practice I realized that there might be some problems regarding the limit. Thank you very much in advance for your support and attention! You will definitely see this library in action on my server, if you want to join discord...

https://discord.gg/czpxHZWBkA

**Comment by jdkDollaR** [comment]
The idea of ​​the include is really very good and very interesting, when I saw this include I was quite excited but when I put it into practice I realized that there might be some problems regarding the limit. Thank you very much in advance for your support and attention! You will definitely see this library in action on my server, if you want to join discord...

https://discord.gg/czpxHZWBkA
